
# Use single quotes instead of double quotes for strings
singleQuote: true

# Use 2 spaces for indentation
tabWidth: 2

# Use trailing commas where valid in objects and arrays
trailingComma: es5

# Print semicolons at the end of statements
semi: true

# Wrap lines at 80 characters
printWidth: 80

# Use the default Prettier parser for JavaScript and TypeScript
parser: 'typescript'
