@startuml

participant User 
participant Frontend
participant API
participant Database 

User ->> Frontend: requests all <font color=green>stopplaces</font>
Frontend ->> API:   <font color=green>stopplaces</font>
API -->> Database:  <font color=purple> query</font>
Database -->> API: <font color=green></font>
API -->> Frontend: <font color=green></font>
Frontend -->> User: <font color=green></font>


User ->> Frontend: selects a <font color=green>stopplace</font>
Frontend ->> API:   <font color=red>platforms</font> from <font color=green>stopplace</font>
API -->> Database:   <font color=purple> query</font>
Database -->> API: <font color=green></font>
API -->> Frontend: <font color=red></font>
Frontend -->> User:  <font color=red></font>

User ->> Frontend: requests <font color=blue>departures</font>
Frontend ->> API:   <font color=blue>departures</font> from <font color=red>platforms</font>
API -->> Database:   <font color=purple> query</font>
Database -->> API: <font color=green></font>
API -->> Frontend: <font color=blue></font>
Frontend -->> User: <font color=blue></font>

@enduml
