@startuml

participant User 
participant WebApplication
participant "PublicTransport API" as PublicTransportAPI

User ->> WebApplication: requests all <font color=green>stopplaces</font>
WebApplication ->> PublicTransportAPI: get <font color=green>stopplaces</font>
PublicTransportAPI -->> WebApplication: returns <font color=green>stopplaces</font>
WebApplication -->> User: displays <font color=green>stopplaces</font>

User ->> WebApplication: selects a <font color=red>stopplace</font>
WebApplication ->> PublicTransportAPI: get <font color=red>platforms</font> from <font color=red>stopplace</font>
PublicTransportAPI -->> WebApplication: returns list of <font color=red>platforms</font>
WebApplication -->> User: display <font color=red>platforms</font>

User ->> WebApplication: requests <font color=blue>departures</font>
WebApplication ->> PublicTransportAPI: get <font color=blue>departures</font>
PublicTransportAPI -->> WebApplication: return <font color=blue>departures</font>
WebApplication -->> User: displays <font color=blue>departures</font>

@enduml
